// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelpExplorer
{
    internal sealed partial class Vsix
    {
        public const string Id = "HelpExplorer.c8c773f3-d62f-4717-9b7d-1d3e440a7d53";
        public const string Name = "HelpExplorer";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
