// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelpExplorer
{
    internal sealed partial class Vsix
    {
        public const string Id = "HelpExplorer.c8c773f3-d62f-4717-9b7d-1d3e440a7d53";
        public const string Name = "Help Explorer";
        public const string Description = @"Adds a Help Explorer tool window that provides contextual help and resources. Great for beginners, students, and hobby programmaers alike.";
        public const string Language = "en-US";
        public const string Version = "1.10";
        public const string Author = "Mads Kristensen";
        public const string Tags = "help, tutorials";
    }
}
