// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HelpExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HelpExplorerString = "3fe2213e-0041-46e6-93bb-7db123589c7e";
        public static Guid HelpExplorer = new Guid(HelpExplorerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int TWindowToolbar = 0x1000;
        public const int TWindowToolbarGroup = 0x1050;
        public const int MultipleProjectTypeDisplay = 0x0111;
        public const int MultipleFileTypeDisplay = 0x0112;
        public const int CreateCapabilitiyFile = 0x0113;
    }
}